### ISSUE TITLE
UI crash

### ISSUE THREAD

**Issue by alexbootman** [evernat/dead-code-detector#1]
Trying to run it on MAC:
java -cp dcd.jar:src/main/lib/* dcd.ui.DeadCodeDetectorUI
java.awt.IllegalComponentStateException: The frame is decorated
	at java.awt.Frame.setOpacity(Frame.java:960)
	at java.awt.Window$1.setOpacity(Window.java:4035)
	at com.sun.awt.AWTUtilities.setWindowOpacity(AWTUtilities.java:174)
	at sun.lwawt.macosx.CPlatformWindow$3.applyProperty(CPlatformWindow.java:163)
	at sun.lwawt.macosx.CPlatformWindow$3.applyProperty(CPlatformWindow.java:162)
	at com.apple.laf.ClientPropertyApplicator.applyProperty(ClientPropertyApplicator.java:45)
	at com.apple.laf.ClientPropertyApplicator.propertyChange(ClientPropertyApplicator.java:75)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at java.awt.Component.firePropertyChange(Component.java:8428)
	at javax.swing.JComponent.putClientProperty(JComponent.java:4087)
	at dcd.ui.DeadCodeDetectorUI.setWindowOpacity(DeadCodeDetectorUI.java:169)
	at dcd.ui.DeadCodeDetectorUI.disappear(DeadCodeDetectorUI.java:156)
	at dcd.ui.DeadCodeDetectorUI.showFrame(DeadCodeDetectorUI.java:125)
	at dcd.ui.DeadCodeDetectorUI$3.run(DeadCodeDetectorUI.java:212)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

java -version
java version "1.8.0_102"

**Comment by evernat** [comment]
fixed by b835302 and released in 2.1 which is available at:
https://github.com/evernat/dead-code-detector/releases
